import { GeneratedRoute } from "../../stores/store";

/**
 * Escape XML special characters to prevent XML injection
 */
function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Converts a route to GPX (GPS Exchange Format) XML string
 * @param route - The generated route with coordinates and distance
 * @param routeName - Optional name for the route (defaults to "Generated Route")
 * @returns GPX XML string
 */
export function convertRouteToGPX(
  route: GeneratedRoute,
  routeName: string = "Generated Route"
): string {
  const now = new Date().toISOString();
  const escapedRouteName = escapeXml(routeName);

  // Create waypoints (track points) from coordinates
  const trackPoints = route.coordinates
    .map(([lon, lat]) => {
      return `      <trkpt lat="${lat}" lon="${lon}"></trkpt>`;
    })
    .join("\n");

  const gpxContent = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="PadPlanner" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${escapedRouteName}</name>
    <desc>Route generated by PadPlanner</desc>
    <time>${now}</time>
  </metadata>
  <trk>
    <name>${escapedRouteName}</name>
    <desc>Distance: ${(route.distance / 1000).toFixed(2)} km</desc>
    <trkseg>
${trackPoints}
    </trkseg>
  </trk>
</gpx>`;

  return gpxContent;
}

/**
 * Downloads a route as a GPX file
 * @param route - The generated route to download
 * @param filename - Optional filename (defaults to route-{timestamp}.gpx)
 */
export function downloadRouteAsGPX(
  route: GeneratedRoute,
  filename?: string
): void {
  try {
    const gpxContent = convertRouteToGPX(route);

    // Create filename with timestamp if not provided
    const finalFilename =
      filename ||
      `route-${new Date()
        .toISOString()
        .slice(0, 19)
        .replace(/:/g, "-")}.gpx`;

    // Create blob and download
    const blob = new Blob([gpxContent], { type: "application/gpx+xml" });
    const url = URL.createObjectURL(blob);

    try {
      const link = document.createElement("a");
      link.href = url;
      link.download = finalFilename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } finally {
      URL.revokeObjectURL(url);
    }
  } catch (error) {
    console.error("Failed to download GPX file:", error);
    throw new Error("Failed to download route. Please try again.");
  }
}
